cambioar test

diff --git a/.github/workflows/push-to-ecr.yml b/.github/workflows/push-to-ecr.yml
--- a/.github/workflows/push-to-ecr.yml
+++ b/.github/workflows/push-to-ecr.yml
@@ -35,17 +35,18 @@ jobs:
 
       - name: Verify openapi.json exists
         run: |
-            if [ ! -f ./api-rtr/openapi.json ]; then
-              echo "openapi.json not found!"
-              exit 1
-            else
-              echo "openapi.json generated successfully."
-            fi
+          if [ ! -f ./api-rtr/openapi.json ]; then
+            echo "openapi.json not found!"
+            exit 1
+          else
+            echo "openapi.json generated successfully."
+          fi
 
       - name: Checkout docs branch
         run: |
-            git fetch origin docs
-            git checkout docs || git checkout -b docs
+          git fetch origin docs
+          git checkout docs || git checkout -b docs
+          git pull origin docs --rebase
 
       - name: Copy openapi.json to docs
         run: cp ./api-rtr/openapi.json ./openapi.json
