e

diff --git a/.github/workflows/push-to-ecr.yml b/.github/workflows/push-to-ecr.yml
--- a/.github/workflows/push-to-ecr.yml
+++ b/.github/workflows/push-to-ecr.yml
@@ -33,15 +33,19 @@ jobs:
       - name: Generate Swagger API documentation
         run: python script.py
 
-      - name: Checkout or create docs branch
+      - name: Verify openapi.json exists
         run: |
-            git fetch origin
-            if git rev-parse --verify origin/docs; then
-              git checkout docs
+            if [ ! -f ./api-rtr/openapi.json ]; then
+              echo "openapi.json not found!"
+              exit 1
             else
-              git checkout -b docs
-              git push origin docs
+              echo "openapi.json generated successfully."
             fi
+
+      - name: Checkout docs branch
+        run: |
+            git fetch origin docs
+            git checkout docs || git checkout -b docs
 
       - name: Copy openapi.json to docs
         run: |
